### ISSUE TITLE
[BRIO] Plug and Neck Diameter Variations

### ISSUE THREAD

**Issue by tobiasschuerg** [torwanbukaj/ikea-brio-others-compatible-train-tracks-generator#2]
First: thanks for this fantastic generator!

After printing several switches which called themselves BRIO compatible (but were not) I now actually manages to print something that fits well. 

It's intriguing and amusing that something as seemingly simple as a wooden railway can have so many incompatibilities, even within the same brand.

Our Brio track, which is approximately 5 years old, has a plug diameter of `11.5` and a neck diameter of `12.5`.

![image](https://user-images.githubusercontent.com/1324555/232330185-8e474ddc-f787-45ad-a1c8-8113c3220ded.png)

The default neck value for Brio works well, but the default plug size is too large, in my case. To improve compatibility and make the tracks fit out of the box, it might be beneficial to gather different sizes for each brand and establish an all-encompassing default set per brand. This way, users can achieve better fitting prints without having to adjust settings manually. Hopefully.

**Comment by torwanbukaj** [comment]
Thanks for the positive feedback!

I can tell you that our pretty new IKEA set has a max difference between plug and nest diameters above 1.26mm and min ~1mm. I have to confess I spend some hours measuring dozens of tracks to get some grip on what's going on with these dimensions. I have to say it is quite difficult to find the sweet spot, especially when you have tracks from different "generations". When I thought I found the sweet spot, I tried to print some parts and...had to add some correction factors to make it fit better. I guess this whole topic may be also dependent on a filament is used, a 3D printer calibration etc. This is why I proposed some "default" dimensions but simultaneously I highly recommend to print a tester before printing some bigger parts. It is what it is, I think finding universal dimensions is - unfortunately - impossible.
